//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewsFocusService", ReplyAction="http://tempuri.org/IService1/NewsFocusServiceResponse")]
        string NewsFocusService(string topics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NewsFocusService", ReplyAction="http://tempuri.org/IService1/NewsFocusServiceResponse")]
        System.Threading.Tasks.Task<string> NewsFocusServiceAsync(string topics);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/nearbyhotels", ReplyAction="http://tempuri.org/IService1/nearbyhotelsResponse")]
        string nearbyhotels(string radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/nearbyhotels", ReplyAction="http://tempuri.org/IService1/nearbyhotelsResponse")]
        System.Threading.Tasks.Task<string> nearbyhotelsAsync(string radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication.ServiceReference1.IService1>, WebApplication.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string NewsFocusService(string topics) {
            return base.Channel.NewsFocusService(topics);
        }
        
        public System.Threading.Tasks.Task<string> NewsFocusServiceAsync(string topics) {
            return base.Channel.NewsFocusServiceAsync(topics);
        }
        
        public string nearbyhotels(string radius) {
            return base.Channel.nearbyhotels(radius);
        }
        
        public System.Threading.Tasks.Task<string> nearbyhotelsAsync(string radius) {
            return base.Channel.nearbyhotelsAsync(radius);
        }
    }
}
